# Generated by Django 5.0.1 on 2024-01-29 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0003_blog_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog_post',
            name='blog_cat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myblog.blog_category'),
        ),
    ]
