# Generated by Django 5.0.1 on 2024-02-01 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0004_blog_post_blog_cat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_category',
            name='blogcat_img',
            field=models.ImageField(upload_to='media/images'),
        ),
        migrations.AlterField(
            model_name='blog_post',
            name='cover_img',
            field=models.ImageField(upload_to='media/images'),
        ),
    ]
