# Generated by Django 5.0.1 on 2024-02-01 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0005_alter_blog_category_blogcat_img_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog_likes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like_count', models.IntegerField(default=0)),
                ('blog_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myblog.blog_post')),
            ],
        ),
    ]
