# Generated by Django 5.0.1 on 2024-02-02 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0008_blog_post_blog_comments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog_post',
            old_name='view_count',
            new_name='views_count',
        ),
        migrations.RemoveField(
            model_name='blog_post',
            name='blog_comments',
        ),
        migrations.CreateModel(
            name='blog_comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b_comment', models.CharField(max_length=300)),
                ('blog_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myblog.blog_post')),
            ],
        ),
    ]
