# Generated by Django 5.0.1 on 2024-02-02 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0009_rename_view_count_blog_post_views_count_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog_comments',
            old_name='blog_id',
            new_name='b_id',
        ),
    ]
