# Generated by Django 5.0.1 on 2024-02-05 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0010_rename_blog_id_blog_comments_b_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='blog_comments',
        ),
    ]
