# Generated by Django 5.0.1 on 2024-02-06 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0012_comments'),
    ]

    operations = [
        migrations.DeleteModel(
            name='comments',
        ),
    ]
