# Generated by Django 5.0.1 on 2024-02-06 05:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0013_delete_comments'),
    ]

    operations = [
        migrations.CreateModel(
            name='comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b_comment', models.CharField(max_length=300)),
                ('b_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myblog.blog_post')),
            ],
        ),
    ]
